name: Aptos sdk docs # url: https://aptos-docs.mirage.xyz

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to the production website with the AWS CLI
        working-directory: _site
        env:
          DOMAIN: aptos-docs.mirage.xyz
        run: |
          aws s3 sync --delete ./ s3://$DOMAIN/ --acl public-read --cache-control "public,max-age=600,s-maxage=3600"
